---

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-analyzers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y shellcheck
          sudo apt install -y shfmt
          python -m pip install --upgrade pip
          pip install cmakelang
          sudo apt install -y clang-format-20
          sudo apt install -y libsdl2-dev
          sudo apt install -y libsdl2-ttf-dev
          sudo apt install -y bear
          sudo apt install -y cmake
          sudo apt install -y clang-tidy

      - name: Check shell scripts
        run: ./scripts/ci/shellcheck.sh

      - name: Check CMake files
        run: ./scripts/ci/cmake-check.sh

      - name: Check code formatting
        run: ./scripts/ci/code-format-check.sh

      - name: Lint code
        run: ./scripts/ci/lint.sh

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y cmake
          sudo apt install -y libsdl2-dev
          sudo apt install -y libsdl2-ttf-dev

      - name: Install deps (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install cmake
          brew install sdl2
          brew install sdl2_ttf
          sudo mkdir -p /usr/local/include
          sudo ln -sf /opt/homebrew/include/SDL2 /usr/local/include/SDL2
      - name: Install deps (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        env:
          SDL2_PATH: "C:\\deps\\SDL2"
          SDL2_TTF_PATH: "C:\\deps\\SDL2_ttf"
          CMAKE_PREFIX_PATH: "C:\\deps\\SDL2;C:\\deps\\SDL2_ttf"
          VCPKG_ROOT: "C:\vcpkg"
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          mkdir C:\deps
          curl -L https://github.com/libsdl-org/SDL/releases/download/release-2.28.5/SDL2-devel-2.28.5-VC.zip -o C:\deps\sdl2.zip
          Expand-Archive C:\deps\sdl2.zip C:\deps\sdl2_temp -Force
          $sdl2_dir = Get-ChildItem "C:\deps\sdl2_temp" -Directory | Select-Object -First 1
          Move-Item $sdl2_dir.FullName "C:\deps\SDL2" -Force
          curl -L https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.20.2/SDL2_ttf-devel-2.20.2-VC.zip -o C:\deps\sdl2_ttf.zip
          Expand-Archive C:\deps\sdl2_ttf.zip C:\deps\sdl2_ttf_temp -Force
          $sdl2_ttf_dir = Get-ChildItem "C:\deps\sdl2_ttf_temp" -Directory | Select-Object -First 1
          Move-Item $sdl2_ttf_dir.FullName "C:\deps\SDL2_ttf" -Force

      - name: Build
        run: ./scripts/ci/build.sh
