---

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-analyzers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y shellcheck
          sudo apt install -y shfmt
          python -m pip install --upgrade pip
          pip install cmakelang
          sudo apt install -y clang-format-20
          sudo apt install -y libsdl2-dev
          sudo apt install -y libsdl2-ttf-dev
          sudo apt install -y bear
          sudo apt install -y cmake
          sudo apt install -y clang-tidy

      - name: Check shell scripts
        run: ./scripts/ci/shellcheck.sh

      - name: Check CMake files
        run: ./scripts/ci/cmake-check.sh

      - name: Check code formatting
        run: ./scripts/ci/code-format-check.sh

      - name: Lint code
        run: ./scripts/ci/lint.sh

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y cmake
          sudo apt install -y libsdl2-dev
          sudo apt install -y libsdl2-ttf-dev

      - name: Install deps (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install cmake
          brew install sdl2
          brew install sdl2_ttf
          sudo mkdir -p /usr/local/include
          sudo ln -sf /opt/homebrew/include/SDL2 /usr/local/include/SDL2
      - name: Install deps (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "deps"
          dotnet tool install -g NuGet.CommandLine  
          nuget init .\deps
          nuget sources Add -Name "sdl2-nuget" -Source "https://www.nuget.org/api/v2/"
          nuget install sdl2 -Version 2.28.5 -OutputDirectory "deps" -ExcludeVersion
          nuget install sdl2_ttf -Version 2.20.2 -OutputDirectory "deps" -ExcludeVersion
          Copy-Item -Path "deps\sdl2" -Destination "deps\SDL2" -Recurse -Force
          Copy-Item -Path "deps\sdl2_ttf" -Destination "deps\SDL2_ttf" -Recurse -Force

      - name: Build
        run: ./scripts/ci/build.sh
