name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-analyzers:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt update
        apt install -y shellcheck
        apt install -y shfmt
        apt install -y bear
        apt install -y cmake
        apt install -y clang-format-20
        apt install -y clang-tidy
        python -m pip install --upgrade pip
        pip install cmakelang

    - name: Check shell scripts
      run: ./scripts/ci/shellcheck.sh

    - name: Check CMake files
      run: ./scripts/ci/cmake-check.sh

    - name: Check code formatting
      run: ./scripts/ci/format-check.sh

    - name: Lint code
      run: ./scripts/ci/lint.sh

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install CMake
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          apt update
          apt install -y cmake
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install cmake
        elif [ "$RUNNER_OS" == "Windows" ]; then
          choco install cmake
        fi

    - name: Build
      run: ./scripts/ci/build.sh

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt update
        apt install -y valgrind
        apt install -y lcov

    - name: Run tests and display coverage
      run: ./scripts/ci/tests_coverage.sh

    - name: Check tests for leaks
      run: ./scripts/ci/leaks.sh
