name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-analyzers:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt install shellcheck
        apt install shfmt
        apt install bear
        apt install clang-format-20
        apt install clang-tidy
        pip install cmakelang

    - name: Check shell scripts
      run: ./scripts/ci/shellcheck.sh

    - name: Check CMake files
      run: ./scripts/ci/cmake-check.sh

    - name: Check code formatting
      run: ./scripts/ci/format-check.sh

    - name: Lint code
      run: ./scripts/ci/lint.sh

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: ./scripts/ci/build.sh

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt install valgrind
        apt install lcov

    - name: Run tests and display coverage
      run: ./scripts/ci/tests_coverage.sh

    - name: Check tests for leaks
      run: ./scripts/ci/leaks.sh
